### ISSUE TITLE
System.Windows.Markup.XamlParseException was unhandled

### ISSUE THREAD

**Issue by treg-supportkids** [madskristensen/RollupTaskRunner#1]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.21]
### Description

Error:
System.Windows.Markup.XamlParseException was unhandled
Message: An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in WindowsBase.dll
Additional information: Must create DependencySource on same Thread as the DependencyObject.
### Steps to recreate

installed vsix from visualstudiogallery
created rollup.config.js
click on taskrunner tab
### Findings

Downloaded source
compiled debug
installed debug vsix
no crash
compiled release
installed release vsix
no crash
downloaded vsix again from visualstudiogallery
crash

**Comment by madskristensen** [comment]
This should have been fixed in the latest version 1.1.4
