### ISSUE TITLE
Make Task Runner Explorer no responding 

### ISSUE THREAD

**Issue by wangkanai** [madskristensen/RollupTaskRunner#2]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 3
- ASP.NET Core 1.0
- This extension: 1.1.5

### Description
Its cause Visual Studio Task Runner Explorer not responding and then the Visual Studio no responding also.

### Steps to recreate
Place the following `rollup.config.js` in the project root.
```
export default {
    entry: 'app/riversync.js',
    dest: '../js/riversync.js',
    format: 'umd',
    moduleName: 'riversync',
    globals: {
        'rxjs/Observable': 'Rx',
        'rxjs/Subject': 'Rx'
    }
};
```

### Current behavior
not responding and task runner explorer if shows up, it will be a blank screen.

**Comment by madskristensen** [comment]
@wangkanai Can you please verify the fix by installing the latest build from here http://vsixgallery.com/extension/356dbaea-0513-4de0-8343-822a753e771b/

**Comment by wangkanai** [comment]
@madskristensen updated to 1.1.7 and still have the same problem. 
Anyway for me to show you the log or something?

![rollup-hang-task-runner](https://cloud.githubusercontent.com/assets/10666633/21745908/0940d68c-d568-11e6-8a47-36e43e05b471.png)

**Comment by madskristensen** [comment]
It would be very weird if it has anything to do with this extension. If you disable it and restart, will VS still hang?

**Comment by wangkanai** [comment]
if i disabled the extension and the Task Runner Explorer could be open up fine.
This issue happen on all workstations, home and office.

![rollup-visual-studio-disable](https://cloud.githubusercontent.com/assets/10666633/21757486/355b1962-d662-11e6-886b-bcf621a2d132.png)

Right on i'm using the command-line to do `rollup -c rollup.config.js -w` until this extension could work.
