### ISSUE TITLE
System.Windows.Markup.XamlParseException was unhandled

### ISSUE THREAD

**Issue by rubenprins** [madskristensen/RollupTaskRunner#3]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.1.7

### Description
Error: An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll

Additional information: Must create DependencySource on same Thread as the DependencyObject.

(Stacktrace does not mention anything about the extension.)

### Steps to recreate
1. Add rollup.config.js to project folder
2. Open Task Runner Explorer
3. Crash

After this, simply opening the project will crash again. The mere presence of a rollup.config.js is enough to kill Studio, it does not even need to be included in the .csproj. Disabling the extension stops VS from crashing.

**Comment by Graphettion** [comment]
I second this issue. Hopefully it can be fixed soon. Crossing fingers!
